services:
  quizzie:
    image: ${DOCKER_REGISTRY-}quizzie
    build:
      context: .
      dockerfile: ./server/quizzie/Dockerfile

  quizziefrontend:
    # env_file:
    #   - ./client/quizzie/.env
    image: ${DOCKER_REGISTRY-}quizziefrontend
    build:
      context: .
      dockerfile: ./client/quizzie/Dockerfile

  quizzieDb:
    image: postgres

  vault:
    image: ${DOCKER_REGISTRY-}vault
    build:
      context: ./vault

volumes:
  postgres_quizzie:
  vault-data:
  vault-config:
