services:
  quizzie:
    image: ${DOCKER_REGISTRY-}quizzie
    build:
      context: .
      dockerfile: ./server/quizzie/Dockerfile
    networks:
      - quizzie_network

  quizziefrontend:
    # env_file:
    #   - ./client/quizzie/.env
    image: ${DOCKER_REGISTRY-}quizziefrontend
    build:
      context: .
      dockerfile: ./client/quizzie/Dockerfile
    networks:
      - quizzie_network

  quizzieDb:
    image: postgres
    environment:
      POSTGRES_USER: quizzie
      POSTGRES_PASSWORD: quizzie
      POSTGRES_DB: quizzie
    networks:
      - quizzie_network
    volumes:
      - postgres_quizzie:/var/lib/postgresql/data
  
  vault:
    image: ${DOCKER_REGISTRY-}vault
    build:
      context: ./vault
    networks:
      - quizzie_network

networks:
  quizzie_network:


volumes:
  postgres_quizzie:
