services:
  quizzieDb:
    environment:
      POSTGRES_DB: quizzie
      POSTGRES_USER: quizzie
      POSTGRES_PASSWORD: quizzie
    ports:
      - '5432:5432'
    volumes:
      - postgres_quizzie:/var/lib/postgresql/data

  quizzie:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=quizzieDb;Database=quizzie;Username=quizzie;Password=quizzie;Include Error Detail=true
    ports:
      - '9000:8080'
      - '9001:8081'
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  quizziefrontend:
    environment:
      NEXT_PUBLIC_BACKEND_URL: 'http://localhost:8080/api/'
    ports:
      - '3000:3000'
    depends_on:
      - quizzie
    volumes:
      - ${APPDATA}/npm:/home/app/.npm:ro
      - ${APPDATA}/yarn:/home/app/.yarn:ro
