apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizzie-deployment # Name of the deployment
spec:
  replicas: 1 # Number of replicas (instances) of your application
  selector:
    matchLabels:
      app: quizzie
  template:
    metadata:
      labels:
        app: quizzie # Label to identify the application
    spec:
      containers:
        - name: quizzie-container # Name of the container
          image: richy112/quizzieapp:latest # Docker image to use
          ports:
            - containerPort: 8080 # Port your application listens on (matches Dockerfile)
            - containerPort: 8081 # Another port your application listens on (matches Dockerfile)
