apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizzie-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizzie-db
  template:
    metadata:
      labels:
        app: quizzie-db
    spec:
      containers:
      - name: quizzie-db-container
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "$POSTGRES_USER"
        - name: POSTGRES_PASSWORD
          value: "$POSTGRES_PASSWORD"
        - name: POSTGRES_DB
          value: "POSTGRES_DB"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
