apiVersion: v1
kind: Service
metadata:
  name: quizzie-service # Name of the service
spec:
  selector:
    app: quizzie # Match the label defined in the deployment
  ports:
    - name: http # Name for the first port
      protocol: TCP
      port: 8080 # Port on the service (exposed to the outside)
      targetPort: 8080 # Port on the container (matches Dockerfile)
    - name: https # Name for the second port
      protocol: TCP
      port: 8081 # Another port on the service (exposed to the outside)
      targetPort: 8081 # Another port on the container (matches Dockerfile)
  type: LoadBalancer # Type of service (LoadBalancer, NodePort, ClusterIP)
